# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Corbin is a Graphic Designer from New Zealand
email: treehousefilms@gmail.com
description: Graphic designer and digital freelance artist based in Auckland, New Zealand. Professional print, branding and web design. View my portfolio or check out our free Vector Graphics and Creative Suite Software Tutorials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corbin.nz" # the base hostname & protocol for your site
twitter_username: corbsoup
github_username:  corbs

# Build settings
markdown: kramdown
