# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Corbin is a Graphic Designer from New Zealand
email: treehousefilms@gmail.com
description: Graphic designer and digital explorer from New Zealand. Print, Branding and Web Design. View my portfolio or check out our Indesign, Illustrator & Photoshop Creative Cloud CC tutorials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corbin.nz" # the base hostname & protocol for your site
twitter_username: corbsoup
github_username:  corbs

# Build settings
markdown: kramdown
